-- MySQL Script generated by MySQL Workbench
-- 09/16/16 21:32:47
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema alexandra_ryzhevich_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `alexandra_ryzhevich_db` ;

-- -----------------------------------------------------
-- Schema alexandra_ryzhevich_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `alexandra_ryzhevich_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci ;
USE `alexandra_ryzhevich_db` ;

-- -----------------------------------------------------
-- Table `alexandra_ryzhevich_db`.`country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `alexandra_ryzhevich_db`.`country` ;

CREATE TABLE IF NOT EXISTS `alexandra_ryzhevich_db`.`country` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `code` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `country_name_uq` (`name` ASC),
  UNIQUE INDEX `country_code_uq` (`code` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alexandra_ryzhevich_db`.`contact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `alexandra_ryzhevich_db`.`contact` ;

CREATE TABLE IF NOT EXISTS `alexandra_ryzhevich_db`.`contact` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(40) NOT NULL,
  `last_name` VARCHAR(40) NOT NULL,
  `patronymic` VARCHAR(40) NULL,
  `birth_date` DATE NULL,
  `gender` ENUM('MALE', 'FEMALE') NULL,
  `marital_status` ENUM('SINGLE', 'MARRIED', 'DIVORCED', 'WIDOWED') NULL,
  `web_site` VARCHAR(200) NULL,
  `email` VARCHAR(100) NULL,
  `place_of_work` VARCHAR(100) NULL,
  `country_id` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_contact_country1_idx` (`country_id` ASC),
  CONSTRAINT `fk_contact_country1`
    FOREIGN KEY (`country_id`)
    REFERENCES `alexandra_ryzhevich_db`.`country` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alexandra_ryzhevich_db`.`address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `alexandra_ryzhevich_db`.`address` ;

CREATE TABLE IF NOT EXISTS `alexandra_ryzhevich_db`.`address` (
  `country_id` INT UNSIGNED NULL,
  `city` VARCHAR(100) NULL,
  `local_address` VARCHAR(100) NULL,
  `index` VARCHAR(20) NULL,
  `contact_id` INT UNSIGNED NOT NULL,
  INDEX `fk_address_contact_idx` (`contact_id` ASC),
  PRIMARY KEY (`contact_id`),
  INDEX `fk_address_country1_idx` (`country_id` ASC),
  CONSTRAINT `fk_address_contact`
    FOREIGN KEY (`contact_id`)
    REFERENCES `alexandra_ryzhevich_db`.`contact` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_address_country1`
    FOREIGN KEY (`country_id`)
    REFERENCES `alexandra_ryzhevich_db`.`country` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alexandra_ryzhevich_db`.`phone`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `alexandra_ryzhevich_db`.`phone` ;

CREATE TABLE IF NOT EXISTS `alexandra_ryzhevich_db`.`phone` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `operator_code` INT UNSIGNED NULL,
  `phone_number` INT UNSIGNED NOT NULL,
  `type` ENUM('HOME', 'MOBILE', 'WORK') NULL,
  `comment` VARCHAR(300) NULL,
  `contact_id` INT UNSIGNED NOT NULL,
  `country_id` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_phone_contact1_idx` (`contact_id` ASC),
  INDEX `fk_phone_country1_idx` (`country_id` ASC),
  CONSTRAINT `fk_phone_contact1`
    FOREIGN KEY (`contact_id`)
    REFERENCES `alexandra_ryzhevich_db`.`contact` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_phone_country1`
    FOREIGN KEY (`country_id`)
    REFERENCES `alexandra_ryzhevich_db`.`country` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alexandra_ryzhevich_db`.`attachment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `alexandra_ryzhevich_db`.`attachment` ;

CREATE TABLE IF NOT EXISTS `alexandra_ryzhevich_db`.`attachment` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `download_date` TIMESTAMP NULL,
  `comment` VARCHAR(300) NULL,
  `contact_id` INT UNSIGNED NOT NULL,
  `path` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_attachment_contact1_idx` (`contact_id` ASC),
  CONSTRAINT `fk_attachment_contact1`
    FOREIGN KEY (`contact_id`)
    REFERENCES `alexandra_ryzhevich_db`.`contact` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alexandra_ryzhevich_db`.`photo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `alexandra_ryzhevich_db`.`photo` ;

CREATE TABLE IF NOT EXISTS `alexandra_ryzhevich_db`.`photo` (
  `path` VARCHAR(255) NOT NULL,
  `contact_id` INT UNSIGNED NOT NULL,
  INDEX `fk_photo_contact1_idx` (`contact_id` ASC),
  PRIMARY KEY (`contact_id`),
  CONSTRAINT `fk_photo_contact1`
    FOREIGN KEY (`contact_id`)
    REFERENCES `alexandra_ryzhevich_db`.`contact` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- ------------add user------------------------

CREATE USER 'alex_ryzhevich'@'localhost' IDENTIFIED BY 'password';
GRANT SELECT ON alexandra_ryzhevich_db.* TO 'alex_ryzhevich'@'localhost';
GRANT DELETE ON alexandra_ryzhevich_db.* TO 'alex_ryzhevich'@'localhost';
GRANT UPDATE ON alexandra_ryzhevich_db.* TO 'alex_ryzhevich'@'localhost';
GRANT INSERT ON alexandra_ryzhevich_db.* TO 'alex_ryzhevich'@'localhost';
FLUSH PRIVILEGES;

-- -----------fill countries--------------------

INSERT INTO `country`(`name`, `code`) VALUES ('Russia', 7);
INSERT INTO `country`(`name`, `code`) VALUES ('GB', 44);
INSERT INTO `country`(`name`, `code`) VALUES ('Germany', 49);
INSERT INTO `country`(`name`, `code`) VALUES ('Belarus', 375);